### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Pukimaa** [tako-discord/kayano#36]

**Comment by Pukimaa** [comment]
Now added Croation Translation (#39)

**Comment by Pukimaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Translation](https://trello.com/c/feEMM4kT/2-translation)

**Comment by Pukimaa** [comment]
Will be reworked at a later point. For now it will stay closed!

**Comment by Pukimaa** [comment]
Resolved with the rewrite.
You can start translating at [translate.tako.rocks](https://translate.tako.rocks/)

**Comment by jaavierdz** [comment]
added Spanish
